#!/usr/bin/env php
<?php


require dirname(__DIR__) . '/vendor/autoload.php';

use Optopus\Options;

$options = new Options($argv);

$options->add('--foo')
	->alias('-f')
	->requiresArgument();

$options->add('--bar')
	->alias('-b')
	->acceptsArgument();

$options->add('--baz')
	->alias('-z')
	->acceptsArgument();

$options->add('--quux')
	->alias('-q')
	->acceptsArgument();

$options->add('--waldo')
	->alias('-w')
	->acceptsArgument();

$options->add('--corge')
	->alias('-c')
	->acceptsArgument()
	->required();

$options->add('--verbose')
	->alias('-v')
	->repeats();

$options->add('--kablammo')
	->alias('-k');

$options->parse();

print_r($options);

