#!/usr/bin/env php
<?php


require dirname(__DIR__) . '/vendor/autoload.php';

use Optopus\Options;

$options = new Options($argv);

$options->add('--foo')
	->alias('-f')
	->requiresArgument()
	->description('Foo.  does foo things');

$options->add('--bar')
	->alias('-b')
	->acceptsArgument();

$options->add('--baz')
	->alias('-z')
	->acceptsArgument();

$options->add('--quux')
	->alias('-q')
	->acceptsArgument();

$options->add('--waldo')
	->alias('-w')
	->acceptsArgument();

$options->add('--corge')
	->alias('-c')
	->acceptsArgument();

$options->add('--xray')
	->alias('-x');

$options->add('--yellow')
	->alias('-y')
	->incompatibleWith(['-x']);

$options->add('--verbose')
	->alias('-v');

$options->add('--kablammo')
	->alias('-k');

$options->title("./foobar -- Does some things");
$options->parse();

var_dump($options->getArguments());
//print_r($options);

